version: "3.8"

services:
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD="trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
